# Generated by Django 3.2.3 on 2021-10-08 00:26

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('email', models.EmailField(max_length=254, unique=True, verbose_name='email address')),
                ('user_name', models.CharField(max_length=150, unique=True)),
                ('nome', models.CharField(blank=True, max_length=150, verbose_name='Nome')),
                ('sobrenome', models.CharField(blank=True, max_length=50, null=True, verbose_name='Sobrenome')),
                ('bio', models.TextField(blank=True, max_length=500, verbose_name='About')),
                ('genero', models.CharField(blank=True, max_length=50, null=True)),
                ('cpf', models.IntegerField(blank=True, null=True)),
                ('data_nascimento', models.DateField(blank=True, null=True)),
                ('cep', models.IntegerField(blank=True, null=True)),
                ('cidade', models.CharField(blank=True, max_length=50, null=True)),
                ('estado', models.CharField(blank=True, max_length=50, null=True)),
                ('is_staff', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('date_joined', models.DateTimeField(auto_now_add=True, verbose_name='Data da criação')),
                ('last_login', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Ultimo login')),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.Group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.Permission', verbose_name='user permissions')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
